### ISSUE TITLE
Tracklist in album posters isnt the same as in albums

### ISSUE THREAD

**Issue by misopog** [TrueMyst/BeatPrints#22]
For example, Unknown Memory's tracklist looks like this:

![image](https://github.com/user-attachments/assets/0762ac1e-6eb0-48db-ad91-65da571effc5)

yet on the poster it looks like this

![image](https://github.com/user-attachments/assets/c849ea37-8183-4013-bf18-629c58efc141)

**Comment by TrueMyst** [comment]
This isn’t a bug- it’s actually intentional. I didn’t put the tracks in order because some albums have really long track names, which makes it tricky to fit everything perfectly on the poster. To fix this, I shuffle the tracks around and sometimes remove the ones with super long names. It also makes the poster look more dynamic and less like a plain, ordered album list.

But if you want, I can add an option for that

**Comment by misopog** [comment]
if you could please

**Comment by TrueMyst** [comment]
> if you could please

I don't have my setup with me right now, but I'll get to it as soon as I can!

**Comment by TrueMyst** [comment]
@misopog I've added the shuffle option for tracklists in album posters :>

Cheers 👍🏼
